version: "3.3"

services:
  traefik:
    image: traefik:2.9.5
    build:
      context: .
      dockerfile: Dockerfile.traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  xpedia:
    image: xampp:latest
    build:
      context: .
      dockerfile: Dockerfile.xpedia
    ports:
      - "41061:22"
      - "41062:80"