## traefik.yml
log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: ":80"                           

providers:
  file:
    filename: "/etc/traefik/config.yml"       # Link to the dynamic configuration
    watch: true                               # Watch for modifications
  providersThrottleDuration: 10               # Configuration reload requency
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"

